name: CI/CD Automation

on:
  push:
    branches:
      - "feature/**" # Run tests on any feature branch push
  pull_request:
    branches:
      - develop
      - main # Run tests on PRs to develop or main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

  create-pr-to-develop:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref_name != 'develop' && github.ref_name != 'main' && success() # Only run on feature branches if tests pass
    steps:
      - uses: actions/checkout@v4
      - name: Create PR to develop
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          head: ${{ github.ref_name }}
          title: "Auto PR: Merge ${{ github.ref_name }} into develop"
          body: "Automatically created PR after passing tests"

  create-pr-to-main:
    runs-on: ubuntu-latest
    needs: test
    if: github.event.pull_request.base.ref == 'develop' && success()
    steps:
      - uses: actions/checkout@v4
      - name: Create PR to main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: develop
          title: "Auto PR: Merge develop into main"
          body: "Automatically created PR after develop branch tests passed"

  auto-merge-main:
    runs-on: ubuntu-latest
    needs: [create-pr-to-main]
    if: success()
    steps:
      - name: Auto merge PR to main
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'develop',
              base: 'main',
              state: 'open'
            });
            if (prs.data.length > 0) {
              const prNumber = prs.data[0].number;
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                merge_method: 'squash'
              });
              console.log(`Merged PR #${prNumber} to main`);
            } else {
              console.log("No PR to merge");
            }
