name: Develop -> Main (create PR only)

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: "pip"

      - run: pip install -r requirements.txt
      - run: pytest

  create-pr:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Create/Update PR develop -> main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: develop
          branch: bot/develop-to-main
          title: Promote develop -> main
          body: Auto-created after develop passed tests. Manual merge only.
