name: Feature -> Develop (auto PR + auto-merge)

on:
  push:
    branches:
      - feature

concurrency:
  group: feature-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: "pip"

      - run: pip install -r requirements.txt
      - run: pytest

  pr-and-automerge:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Create/Update PR to develop
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          head: ${{ github.ref_name }}
          branch: bot/${{ github.ref_name }}-to-develop
          title: Auto PR: ${{ github.ref_name }} -> develop
          body: Auto-created after tests passed.

      - name: Enable auto-merge (squash) for PR to develop
        if: steps.cpr.outputs.pull-request-number != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = Number('${{ steps.cpr.outputs.pull-request-number }}');

            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            await github.graphql(`
              mutation($prId: ID!) {
                enablePullRequestAutoMerge(input: {pullRequestId: $prId, mergeMethod: SQUASH}) {
                  pullRequest { number }
                }
              }
            `, { prId: pr.data.node_id });